### ISSUE TITLE
Import & Export paths/settings?

### ISSUE THREAD

**Issue by davidhund** [anthonydugois/polynom#2]
Thanks for this awesome little tool. As a matter of fact I have a client that wanted to update a set of paths in a graphic so this could have been very helpful if only you supported im- and exporting the settings/paths ;-)

Could we expect something like this in the future?

**Comment by anthonydugois** [comment]
I'm working on a function to edit the path code manually, but I'm not sure this is what you mean by "import and export the paths". Could you be more specific? :)

**Comment by davidhund** [comment]
Editing the path code manually (and thus being able to copy-paste) is partially what I meant.

Manual editing would allow us to 'load' and 'save' path data (by copy-pasting). This, however, does not handle the SVG 'canvas' dimensions, etc. Pasting path data based on different dimensions would result in in—or partially—visible path's.

It would be better to be able to save all settings: path-data and app-settings (canvas dimensions, etc).
Off the top of my head a simple `svg-path-builder.json` object would be great, but even better would be to (also) have the option to save only the _image_ (`your-paths.svg`).

Absolutely brilliant would be to be able to _import_ an SVG containing path's and make that editable :-)

**Comment by anthonydugois** [comment]
Oh ok, I get it. Well this is an excellent idea. I think the JSON file would be redundant, because you already have all the data in the SVG file.

Export is easy, and I can load paths from an SVG image by parsing the file. I'll add these functions for sure. :)

**Comment by davidhund** [comment]
:+1: :rocket:
