### ISSUE TITLE
Point deletion does not work

### ISSUE THREAD

**Issue by oslego** [anthonydugois/polynom#5]
Issue: pressing `CMD+R` does not delete the active point.

Steps:
- open http://anthonydugois.com/svg-path-builder/ 
- click any point in active path
- press `CMD+R`

Expected: current selected point should be deleted.

System: Chrome 47 (beta), Mac OSX 10.11

**Comment by anthonydugois** [comment]
Hum yeah, unfortunately I can't test shortcuts on mac. I noticed problems on windows too with the preventing system. I think I will avoid completely the use of `Ctrl` or `CMD` keys, but I don't know what shortcuts would be relevant.

Do you have any suggestion?

**Comment by oslego** [comment]
Use for `Ctrl` for shortcuts on Mac is relatively safe. It doesn't clash with system-wide shortcuts like `Cmd` does.

For example:
`Cmd + Q` =  quit browser
`Cmd + P` =  print page
`Cmd + R` = reload page
`Cmd + T` =  new tab

I have seen other web apps do OS detection and alternate between `Ctrl` and `Cmd` for Mac/Linux and Windows, respectively. Of course, this needs to be tested.

**Comment by oslego** [comment]
The `option` (alt) key may be a viable middle-ground to suit all systems.

**Comment by iclanzan** [comment]
Why not use letters without any modifier keys? That is the simplest solution to implement and doesn’t require different configuration for Windows/Mac. Also, apps like Gmail and Github use just letters for most shortcuts.

**Comment by anthonydugois** [comment]
Well, I think the letters without modifier keys is the most appropriate solution and would fit to any platform. How about this : 
- `A + Click` = add a point
- `D` = delete active point
- `P` = add a path
- `R` = remove active path
- `N` = select next point on active path

Feel free to propose other shortcuts if you have any idea.

**Comment by oslego** [comment]
Maybe have a look at popular vector editing tools to see how they handle this. Keep in mind the user's flow. 

Without deep experience in design tools, here's what _feels_ in flow to me:

**Points**
Select point: click it
Add point: click anywhere on canvas, but not on existing points
Remove selected point: `backspace` / delete key
Move point (fine-grained adjustments): arrow keys
Select prev / next point: `Shift` + arrow keys (left / right)

**Paths**
Select path: click on edges of path, not points
Remove selected path: backspace / delete key
Add new path: use sidebar UI (is there a need for a keyboard shortcut?)
Add intermediary point on an edge: `Alt` /  `Shift` + click

Again, these are just suggestions. But I recommend trying to follow conventions of existing tools to make it easier for people to adapt.

**Comment by anthonydugois** [comment]
It's impossible to select a path without select its points, so I can't use the same shortcut to delete a path and a point. But your suggestions are great, I will take a look on the behavior of tools in Adobe Illustrator or Inkscape. Thank you for your help.

**Comment by oslego** [comment]
Why would that be impossible? It looks like right now, clicking on a path does select it and, in addition, it also selects the nearest point on that path. 

Perhaps this heuristic works: if the click wasn't directly on a point, just the path is selected. There's a valuable use case for this too: the ability to move/drag the whole path to reposition it.

I'm only trying to provide feedback on usability. You are, of course, free to accept or reject these suggestions.
